# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'SwiftDigitalAnalyticsPages' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDigitalAnalyticsPages

   pod 'DigitalAnalyticsDebug'

  target 'SwiftDigitalAnalyticsPagesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftDigitalAnalyticsPagesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
